<?php

namespace Buepro\Easyconf\Form\Container;

class PaletteAndSingleContainer extends \TYPO3\CMS\Backend\Form\Container\PaletteAndSingleContainer
{
    protected function wrapSingleFieldContentWithLabelAndOuterDiv(array $element, array $additionalPaletteClasses = []): string
    {
        if($colClass = $this->data['processedTca']['columns'][$element['fieldName']]['colClass'] ?? false) {
            $additionalPaletteClasses = [$colClass];
        }
        return parent::wrapSingleFieldContentWithLabelAndOuterDiv($element, $additionalPaletteClasses); // TODO: Change the autogenerated stub
    }

}
